[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alamode"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
]
